### ISSUE TITLE
Remove selectable text where appropriate

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#310]
Text selection ought to be turned off in places it is unhelpful and could be frustrating while dragging around other things, like in menus and buttons.

![image](https://cloud.githubusercontent.com/assets/1119165/22225642/e721cf02-e188-11e6-9f16-d8bff793e745.png)

It isn't fixed in T-PEN Classic, so it isn't that important.

**Comment by thehabes** [comment]
As of January 2017:
The user-select is currently supported in all browsers except Internet Explorer 9 and earlier versions (but sadly still needs a vendor prefix).
All of the correct CSS variations are:
```css
button, .unselectable, i  {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari*/
     -khtml-user-select: none; /* Konqueror */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}
```
Note that it's a non-standard feature (i.e. not a part of any specification). It is not guaranteed to work everywhere, and there might be differences in implementation among browsers and in the future browsers can drop support for it.
